### ISSUE TITLE
Plugin crashes when enabling on Blender 3.5

### ISSUE THREAD

**Issue by WisteriaSp** [Pherakki/BlenderToolsForGFS#124]
**Describe the bug**
Plugin crashes when trying to enable it on Blender 3.5

**To Reproduce**
1. Open Blender 3.5
2. Install the plugin
3. Enable it

**Expected behavior**
It shouldn't crash

**Files**
If importing or exporting an unedited vanilla file, provide the name of the file. If exporting a blend file, either provide the blend or describe exactly how to trigger the bug such that the blend file can be reproduced.

**Additional context**
Works fine on blender 2.92
Log:
Exception in module register(): C:\Users\Wisteria\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\BlenderToolsForGFS\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\Wisteria\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\BlenderToolsForGFS\__init__.py", line 143, in register
    CLASSES, PROP_GROUPS, LIST_ITEMS = init_bpy()
  File "C:\Users\Wisteria\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\BlenderToolsForGFS\__init__.py", line 35, in init_bpy
    from .src.BlenderIO.Properties.Model         import ModelBoundingBox
ImportError: cannot import name 'ModelBoundingBox' from 'BlenderToolsForGFS.src.BlenderIO.Properties.Model' (C:\Users\Wisteria\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\BlenderToolsForGFS\src\BlenderIO\Properties\Model.py)

**Comment by Pherakki** [comment]
1. Is this with v0.1.1 or develop?
2. When upgrading, did you do so in a clean environment, _i.e._
    1. Uninstall plugin in Addons
    2. Close Blender
    3. Re-open Blender
    4. Install new plugin?

**Comment by WisteriaSp** [comment]
This is with v0.1.1 and I did so in a clean environment - strangely enough the develop version seems to work fine so perhaps its fixed?

**Comment by Pherakki** [comment]
I can't reproduce this on Blender 3.5, and the fact that it installs ok on Blender 2.92 really suggests to me that this is an environment issue.
I don't mean to doubt you, but are you *absolutely* certain that you closed Blender after uninstalling v0.1, and then re-opened a new instance a Blender before installing the new version of the plugin?

This environmental issue will be caused by the plugin not being hot-reloadable within the Blender ecosystem yet since I don't have a satisfactory way of doing it yet for such a huge plugin. I'll make an issue about it regardless.

Would you be willing to check once more if v0.1.1 installs correctly if you carefully follow the four steps I outlined in the previous comment?

The `develop` branch has a number of undocumented changes (prime amongst these currently being that meshes are now imported and exported as a flat list, with some extra optional Custom Properties) which may be unfamiliar to work with without additional documentation if you're used to v0.1. There shouldn't be any hidden nasty surprises - these are mostly 'advanced' features most people don't need to dig into - it's just different (and probably less stable than v0.1.1 since it's the bleeding edge of development).

**Comment by WisteriaSp** [comment]
Seems to install fine now after following those steps again, must've been a mistake on my end. Thanks for helping!

**Comment by Pherakki** [comment]
Great, thanks for confirming. I'll make a ticket to make the plugin hot-reloadable (hopefully in time for v0.2) so that you don't have to close Blender between reinstalls.
